import { useEffect, useState } from "react";
import { ScrollView, Text, StyleSheet, View, RefreshControl } from "react-native";
import BackNavButton from "../../src/components/BackNavButton";
import PageHeader from "../../src/components/PageHeader";
import FormSection from "../../src/components/FormSection";
import AppButton from "../../src/components/AppButton";
import EmptyStateCard from "../../src/components/EmptyStateCard";
import StatusBadge from "../../src/components/StatusBadge";
import RoleGuard from "../../src/components/RoleGuard";
import { useAppTheme } from "../../src/context/ThemeContext";
import { useToast } from "../../src/context/ToastContext";
import {
  getSystemAlertsService,
  resolveSystemAlertService,
  runAutomationChecksService,
} from "../../src/services/systemAlertService";

function getSeverityType(severity) {
  switch (severity) {
    case "CRITICAL":
      return "danger";
    case "HIGH":
      return "warning";
    case "MEDIUM":
      return "info";
    default:
      return "neutral";
  }
}

export default function AdminSystemAlertsScreen() {
  const { colors, typography, radius, spacing, shadow } = useAppTheme();
  const { showToast } = useToast();

  const [alerts, setAlerts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [isRunning, setIsRunning] = useState(false);
  const [resolvingId, setResolvingId] = useState(null);

  const loadAlerts = async (refresh = false) => {
    try {
      refresh ? setIsRefreshing(true) : setIsLoading(true);
      const data = await getSystemAlertsService({ status: "OPEN" });
      setAlerts(data || []);
    } catch (error) {
      showToast({
        title: "Alerts Load Failed",
        message: error.message || "Unable to load system alerts.",
        type: "error",
      });
    } finally {
      setIsLoading(false);
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const handleRunChecks = async () => {
    try {
      setIsRunning(true);
      const data = await runAutomationChecksService();

      showToast({
        title: "Checks Complete",
        message: `${data?.count || 0} alert(s) checked or created.`,
        type: "success",
      });

      await loadAlerts(true);
    } catch (error) {
      showToast({
        title: "Checks Failed",
        message: error.message || "Unable to run automation checks.",
        type: "error",
      });
    } finally {
      setIsRunning(false);
    }
  };

  const handleResolve = async (alertId) => {
    try {
      setResolvingId(alertId);
      await resolveSystemAlertService(alertId);

      showToast({
        title: "Alert Resolved",
        message: "The system alert was marked as resolved.",
        type: "success",
      });

      await loadAlerts(true);
    } catch (error) {
      showToast({
        title: "Resolve Failed",
        message: error.message || "Unable to resolve alert.",
        type: "error",
      });
    } finally {
      setResolvingId(null);
    }
  };

  return (
    <RoleGuard allowedRoles={["ADMIN"]}>
      <ScrollView
        contentContainerStyle={[styles.container, { backgroundColor: colors.background }]}
        refreshControl={
          <RefreshControl refreshing={isRefreshing} onRefresh={() => loadAlerts(true)} />
        }
      >
        <BackNavButton label="Back to Admin Dashboard" fallbackRoute="/admin" />

        <PageHeader
          eyebrow="Automation"
          title="System Alerts"
          subtitle="Review and resolve operational alerts generated by automation checks."
          icon="alert-circle-outline"
        />

        <FormSection title="Actions">
          <AppButton
            title={isRunning ? "Running Checks..." : "Run Automation Checks"}
            onPress={handleRunChecks}
            loading={isRunning}
            disabled={isRunning}
          />
        </FormSection>

        <FormSection title="Open Alerts">
          {isLoading ? (
            <Text style={[typography.body, { color: colors.textMuted }]}>
              Loading alerts...
            </Text>
          ) : alerts.length ? (
            alerts.map((alert) => (
              <View
                key={alert.id}
                style={[
                  styles.card,
                  {
                    backgroundColor: colors.surface,
                    borderColor: colors.border,
                    borderRadius: radius.lg,
                    padding: spacing.md,
                  },
                  shadow,
                ]}
              >
                <View style={styles.headerRow}>
                  <Text style={[styles.cardTitle, { color: colors.text }]}>
                    {alert.alertType}
                  </Text>
                  <StatusBadge
                    label={alert.severity}
                    type={getSeverityType(alert.severity)}
                  />
                </View>

                <Text style={[typography.body, { color: colors.text }]}>
                  {alert.message}
                </Text>

                {alert.incident ? (
                  <Text style={[typography.body, { color: colors.textMuted }]}>
                    Incident: {alert.incident.trackingCode}
                  </Text>
                ) : null}

                {alert.patient ? (
                  <Text style={[typography.body, { color: colors.textMuted }]}>
                    Patient: {alert.patient.patientCode}
                  </Text>
                ) : null}

                {alert.resourceRequest ? (
                  <Text style={[typography.body, { color: colors.textMuted }]}>
                    Resource: {alert.resourceRequest.resourceCategory?.name || "Request"}
                  </Text>
                ) : null}

                {alert.resourceItem ? (
                  <Text style={[typography.body, { color: colors.textMuted }]}>
                    Stock: {alert.resourceItem.subType || alert.resourceItem.label}
                  </Text>
                ) : null}

                <Text style={[typography.body, { color: colors.textMuted }]}>
                  Created: {new Date(alert.createdAt).toLocaleString()}
                </Text>

                <AppButton
                  title={resolvingId === alert.id ? "Resolving..." : "Resolve Alert"}
                  onPress={() => handleResolve(alert.id)}
                  loading={resolvingId === alert.id}
                  disabled={resolvingId === alert.id}
                  variant="secondary"
                />
              </View>
            ))
          ) : (
            <EmptyStateCard
              title="No Open Alerts"
              message="No unresolved system alerts are currently open."
              icon="checkmark-circle-outline"
            />
          )}
        </FormSection>
      </ScrollView>
    </RoleGuard>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 24,
    flexGrow: 1,
  },
  card: {
    borderWidth: 1,
    marginBottom: 12,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 8,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
});