export const MOCK_INCIDENTS = [
  {
    id: "INC-001",
    trackingCode: "MDF-184230",
    incidentType: "Road Accident",
    location: "Wandegeya, Kampala",
    autoLocationText: "Wandegeya, Kampala, Uganda",
    manualLocationText: "Near Wandegeya Market",
    latitude: 0.333611,
    longitude: 32.568611,
    victims: 3,
    status: "Received",
    reportedAt: "2026-04-06 09:10 AM",
    reportedAtISO: "2026-04-06T09:10:00",
    source: "Public Report",
    reporterPhone: "0701234567",
    notes: "Three victims involved in a boda-boda collision.",
    mediaCount: 2,
    statusHistory: [
      { id: "h1", label: "Received", time: "09:10 AM" },
    ],
  },
  {
    id: "INC-002",
    trackingCode: "MDF-552781",
    incidentType: "Medical Emergency",
    location: "Mulago Hill Road, Kampala",
    autoLocationText: "Mulago Hill Road, Kampala, Uganda",
    manualLocationText: "Outside main gate",
    latitude: 0.341111,
    longitude: 32.576944,
    victims: 1,
    status: "Accepted",
    reportedAt: "2026-04-06 09:22 AM",
    reportedAtISO: "2026-04-06T09:22:00",
    source: "Public Report",
    reporterPhone: "0787654321",
    notes: "Patient collapsed and is unconscious.",
    mediaCount: 0,
    statusHistory: [
      { id: "h1", label: "Received", time: "09:22 AM" },
      { id: "h2", label: "Accepted", time: "09:27 AM" },
    ],
  },
  {
    id: "INC-003",
    trackingCode: "MDF-903114",
    incidentType: "Fire Outbreak",
    location: "Kisenyi, Kampala",
    autoLocationText: "Kisenyi, Kampala, Uganda",
    manualLocationText: "Near Kisenyi taxi stage",
    latitude: 0.306944,
    longitude: 32.563611,
    victims: 5,
    status: "Under Review",
    reportedAt: "2026-04-06 09:35 AM",
    reportedAtISO: "2026-04-06T09:35:00",
    source: "Public Report",
    reporterPhone: "",
    notes: "Smoke inhalation and burn injuries reported.",
    mediaCount: 1,
    statusHistory: [
      { id: "h1", label: "Received", time: "09:35 AM" },
      { id: "h2", label: "Under Review", time: "09:40 AM" },
    ],
  },
  {
    id: "INC-004",
    trackingCode: "MDF-777201",
    incidentType: "Violence/Assault",
    location: "Nakawa, Kampala",
    autoLocationText: "Nakawa, Kampala, Uganda",
    manualLocationText: "Near police post",
    latitude: 0.334444,
    longitude: 32.622222,
    victims: 2,
    status: "Response In Progress",
    reportedAt: "2026-04-06 09:48 AM",
    reportedAtISO: "2026-04-06T09:48:00",
    source: "Public Report",
    reporterPhone: "0755001122",
    notes: "Two injured after assault. One bleeding heavily.",
    mediaCount: 0,
    statusHistory: [
      { id: "h1", label: "Received", time: "09:48 AM" },
      { id: "h2", label: "Accepted", time: "09:50 AM" },
      { id: "h3", label: "Response In Progress", time: "09:55 AM" },
    ],
  },
  {
    id: "INC-005",
    trackingCode: "MDF-301844",
    incidentType: "Other",
    location: "Bwaise, Kampala",
    autoLocationText: "Bwaise, Kampala, Uganda",
    manualLocationText: "Near drainage channel",
    latitude: 0.356944,
    longitude: 32.557500,
    victims: 1,
    status: "Duplicate",
    reportedAt: "2026-04-06 10:02 AM",
    reportedAtISO: "2026-04-06T10:02:00",
    source: "Public Report",
    reporterPhone: "",
    notes: "Duplicate flooding-related injury report.",
    mediaCount: 0,
    statusHistory: [
      { id: "h1", label: "Received", time: "10:02 AM" },
      { id: "h2", label: "Duplicate", time: "10:05 AM" },
    ],
  },
];